import turtle
pen = turtle.Turtle()
pen.color('red')
pen.begin_fill()
pen.fillcolor('red')
pen.circle(200)
pen.end_fill()
pen.ht()
square = turtle.Turtle()
square.color('blue')
square.begin_fill()
square.fillcolor('blue')
l = 142
square.penup()
square.goto(0, 60)
square.pendown()
square.forward(l)
square.left(90)
for i in range(3):
    square.forward(2*l)
    square.left(90)
square.forward(l)
square.end_fill()
square.ht()
turtle.exitonclick()
